"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.append(str(BASE_DIR.parent.parent.parent.parent))

from common.env import (
    DJANGO_SECRET_KEY,
    DJANGO_DEBUG,
    DJANGO_ALLOWED_HOSTS,
    DJANGO_CORS_ALLOW_ALL_ORIGINS,
    DJANGO_TIME_ZONE,
    ES_HOST,
    ES_PORT,
    ES_USER,
    ES_PASSWORD,
    ES_USE_SSL,
    ES_VERIFY_CERTS,
    AGENT_FASTAPI_BASE,
)

SECRET_KEY = DJANGO_SECRET_KEY

DEBUG = DJANGO_DEBUG

ALLOWED_HOSTS = DJANGO_ALLOWED_HOSTS.split(',')


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = DJANGO_TIME_ZONE

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = DJANGO_CORS_ALLOW_ALL_ORIGINS

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

ELASTICSEARCH_HOST = ES_HOST
ELASTICSEARCH_PORT = ES_PORT
ELASTICSEARCH_USER = ES_USER
ELASTICSEARCH_PASSWORD = ES_PASSWORD
ELASTICSEARCH_USE_SSL = ES_USE_SSL
ELASTICSEARCH_VERIFY_CERTS = ES_VERIFY_CERTS

# Agent Service 反代目标(Django → FastAPI :8001,对内)
# 值来自 common.env 的 AGENT_FASTAPI_BASE(按 AE_BACKEND_HOST/PORT 计算默认,可在 .env 覆盖)
# 已在顶部 import 中引入,settings.AGENT_FASTAPI_BASE 可直接使用。
