"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path

import pymysql
pymysql.install_as_MySQLdb()
# Django 6 mysql backend 要求 mysqlclient>=2.2.1,PyMySQL 通过版本欺骗绕过检查
pymysql.version_info = (2, 2, 1, 'final', 0)
pymysql.__version__ = '2.2.1'

BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.append(str(BASE_DIR.parent.parent.parent.parent))

from common.env import (
    DJANGO_SECRET_KEY,
    DJANGO_DEBUG,
    DJANGO_ALLOWED_HOSTS,
    DJANGO_CORS_ALLOW_ALL_ORIGINS,
    DJANGO_TIME_ZONE,
    ES_HOST,
    ES_PORT,
    ES_USER,
    ES_PASSWORD,
    ES_USE_SSL,
    ES_VERIFY_CERTS,
    AGENT_FASTAPI_BASE,
    MYSQL_HOST,
    MYSQL_PORT,
    MYSQL_DATABASE,
    MYSQL_USER,
    MYSQL_PASSWORD,
    JWT_SECRET_KEY,
    JWT_ACCESS_TTL_MINUTES,
    JWT_REFRESH_TTL_DAYS,
    JWT_ROTATE_REFRESH,
    JWT_BLACKLIST_AFTER_ROTATION,
)

SECRET_KEY = DJANGO_SECRET_KEY

DEBUG = DJANGO_DEBUG

ALLOWED_HOSTS = DJANGO_ALLOWED_HOSTS.split(',')


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'api',
    'accounts',
    'incident_management',
    'reports',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'backend.middleware.ApiTrailingSlashMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DATABASE,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASSWORD,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = DJANGO_TIME_ZONE

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = DJANGO_CORS_ALLOW_ALL_ORIGINS

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 自定义:在 SimpleJWT 基础上额外校验 is_active,禁用用户旧 JWT 立即失效
        'accounts.authentication.ActiveUserJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta
SIMPLE_JWT = {
    'SIGNING_KEY': JWT_SECRET_KEY,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=JWT_ACCESS_TTL_MINUTES),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_TTL_DAYS),
    'ROTATE_REFRESH_TOKENS': JWT_ROTATE_REFRESH,
    'BLACKLIST_AFTER_ROTATION': JWT_BLACKLIST_AFTER_ROTATION,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS 显式允许 Authorization 头(AllowAll=True 时默认全开,这里更稳妥)
CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
]

ELASTICSEARCH_HOST = ES_HOST
ELASTICSEARCH_PORT = ES_PORT
ELASTICSEARCH_USER = ES_USER
ELASTICSEARCH_PASSWORD = ES_PASSWORD
ELASTICSEARCH_USE_SSL = ES_USE_SSL
ELASTICSEARCH_VERIFY_CERTS = ES_VERIFY_CERTS

# Agent Service 反代目标(Django → FastAPI :8001,对内)
# 值来自 common.env 的 AGENT_FASTAPI_BASE(按 AE_BACKEND_HOST/PORT 计算默认,可在 .env 覆盖)
# 已在顶部 import 中引入,settings.AGENT_FASTAPI_BASE 可直接使用。
