# 关键词模块
from .sql_injection import SQL_INJECTION_KEYWORDS, SQL_INJECTION_PATTERNS
from .xss import XSS_KEYWORDS, XSS_PATTERNS
from .command_injection import COMMAND_INJECTION_KEYWORDS, COMMAND_INJECTION_PATTERNS
from .path_traversal import PATH_TRAVERSAL_KEYWORDS, PATH_TRAVERSAL_PATTERNS
from .csrf import CSRF_KEYWORDS, CSRF_PATTERNS
from .bot import BOT_KEYWORDS, BOT_PATTERNS
from .sensitive_access import SENSITIVE_ACCESS_KEYWORDS, SENSITIVE_ACCESS_PATTERNS

__all__ = [
    'SQL_INJECTION_KEYWORDS',
    'SQL_INJECTION_PATTERNS',
    'XSS_KEYWORDS',
    'XSS_PATTERNS',
    'COMMAND_INJECTION_KEYWORDS',
    'COMMAND_INJECTION_PATTERNS',
    'PATH_TRAVERSAL_KEYWORDS',
    'PATH_TRAVERSAL_PATTERNS',
    'CSRF_KEYWORDS',
    'CSRF_PATTERNS',
    'BOT_KEYWORDS',
    'BOT_PATTERNS',
    'SENSITIVE_ACCESS_KEYWORDS',
    'SENSITIVE_ACCESS_PATTERNS'
]
