version: '3.8'

services:
  zookeeper:
      image: confluentinc/cp-zookeeper:7.4.0
      container_name: zookeeper
      environment:
        - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_PORT:-2181}
      volumes:
        - zk_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "${KAFKA_PORT:-29092}:${KAFKA_PORT:-29092}"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:${KAFKA_PORT:-29092}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:${KAFKA_PORT:-29092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - kafka_data:/var/lib/kafka/data
  
  kafka-connect:
    build: ./config/kafka-connect
    container_name: kafka-connect
    hostname: kafka-connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"

    environment:
      # Kafka
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092

      # REST API
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect

      # Worker
      CONNECT_GROUP_ID: connect-cluster

      # Internal Topics
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # Converters
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # Connector Plugins
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "${ES_PORT:-19200}:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data 

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - KAFKA_TOPIC_RAW=${KAFKA_TOPIC_RAW:-log.raw}
      - KAFKA_TOPIC_STRUCTURED=${KAFKA_TOPIC_STRUCTURED:-log.structured}

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  kafka_data:
    name: system_audit_kafka_data
  es_data:
    name: system_audit_es_data
  zk_data:
    name: system_audit_zk_data