# Generated by Django 6.0.7 on 2026-09-09 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=128, unique=True, verbose_name='外部事件ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('severity', models.CharField(choices=[('low', '低危'), ('medium', '中危'), ('high', '高危'), ('critical', '严重')], default='medium', max_length=16, verbose_name='严重等级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('investigating', '调查中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=16, verbose_name='状态')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='源IP')),
                ('source_path', models.CharField(blank=True, default='', max_length=2048, verbose_name='请求路径')),
                ('agent_summary', models.TextField(blank=True, default='', verbose_name='Agent分析摘要')),
                ('agent_recommendations', models.JSONField(blank=True, default=list, verbose_name='Agent处置建议')),
                ('agent_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Agent分析时间')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '安全事件',
                'verbose_name_plural': '安全事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '创建事件'), ('assigned', '指派负责人'), ('status_changed', '状态变更'), ('comment', '处置记录'), ('agent_analyzed', 'Agent分析')], max_length=32, verbose_name='动作')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incident_management.incident', verbose_name='所属事件')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_timelines', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '事件时间线',
                'verbose_name_plural': '事件时间线',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity', '-created_at'], name='idx_inc_workbench'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assignee', 'status'], name='idx_inc_assignee'),
        ),
        migrations.AddIndex(
            model_name='incidenttimeline',
            index=models.Index(fields=['incident', 'created_at'], name='idx_timeline_inc'),
        ),
    ]
