# Generated by Django 6.0.7 on 2026-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True, verbose_name='事件ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='源IP')),
                ('path', models.CharField(blank=True, default='', max_length=2048, verbose_name='请求路径')),
                ('method', models.CharField(blank=True, default='', max_length=16, verbose_name='HTTP方法')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='HTTP状态码')),
                ('user_agent', models.CharField(blank=True, default='', max_length=1024, verbose_name='User-Agent')),
                ('detect_type', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='规则攻击类型')),
                ('risk_level', models.CharField(choices=[('critical', '严重'), ('high', '高危'), ('medium', '中危'), ('low', '低危'), ('normal', '正常'), ('unknown', '未知')], db_index=True, default='unknown', max_length=16, verbose_name='风险等级')),
                ('risk_score', models.IntegerField(default=0, verbose_name='风险评分')),
                ('attack_type_ai', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='AI攻击类型')),
                ('summary', models.TextField(blank=True, default='', verbose_name='分析摘要')),
                ('reasoning', models.JSONField(blank=True, default=list, verbose_name='推理过程')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='处置建议')),
                ('log_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='日志时间')),
                ('analysis_timestamp', models.DateTimeField(db_index=True, verbose_name='分析时间')),
                ('ingestion_time', models.DateTimeField(db_index=True, verbose_name='摄入时间')),
                ('raw_response', models.JSONField(blank=True, default=None, null=True, verbose_name='LLM原始响应')),
                ('original_log', models.JSONField(blank=True, default=None, null=True, verbose_name='原始消息快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI分析报告',
                'verbose_name_plural': 'AI分析报告',
                'db_table': 'analysis_report',
                'ordering': ['-analysis_timestamp'],
                'indexes': [models.Index(fields=['risk_level', '-analysis_timestamp'], name='idx_report_risk_ts'), models.Index(fields=['ip', '-analysis_timestamp'], name='idx_report_ip_ts')],
            },
        ),
    ]
