# Generated by Django 6.0.7 on 2026-09-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('correct', '报告正确'), ('false_positive', '误报'), ('partially_correct', '部分正确'), ('uncertain', '无法判定')], max_length=32, verbose_name='报告正确性')),
                ('category', models.CharField(choices=[('real_attack', '真实攻击'), ('scanner_probe', '扫描探测'), ('normal_business', '正常业务'), ('rule_misfire', '规则误报'), ('ai_misjudgment', 'AI误判'), ('other', '其他')], max_length=32, verbose_name='实际情况')),
                ('actions', models.JSONField(blank=True, default=list, verbose_name='处置动作')),
                ('comment', models.TextField(verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次处理时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近改判时间')),
            ],
            options={
                'verbose_name': '报告审核结论',
                'verbose_name_plural': '报告审核结论',
                'db_table': 'report_review',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', '首次审核'), ('revised', '改判')], max_length=16, verbose_name='变更类型')),
                ('verdict', models.CharField(choices=[('correct', '报告正确'), ('false_positive', '误报'), ('partially_correct', '部分正确'), ('uncertain', '无法判定')], max_length=32)),
                ('category', models.CharField(choices=[('real_attack', '真实攻击'), ('scanner_probe', '扫描探测'), ('normal_business', '正常业务'), ('rule_misfire', '规则误报'), ('ai_misjudgment', 'AI误判'), ('other', '其他')], max_length=32)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='结论时间')),
            ],
            options={
                'verbose_name': '报告审核历史',
                'verbose_name_plural': '报告审核历史',
                'db_table': 'report_review_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='认领时间'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reports', to=settings.AUTH_USER_MODEL, verbose_name='认领人'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='review_status',
            field=models.CharField(choices=[('pending', '待处理'), ('claimed', '处理中'), ('processed', '已处理')], db_default='pending', default='pending', max_length=16, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['review_status', '-analysis_timestamp'], name='idx_report_review_ts'),
        ),
        migrations.AddField(
            model_name='reportreview',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reports.analysisreport', verbose_name='所属报告'),
        ),
        migrations.AddField(
            model_name='reportreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_reviews', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='reportreviewhistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='reports.analysisreport', verbose_name='所属报告'),
        ),
        migrations.AddField(
            model_name='reportreviewhistory',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_review_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportreviewhistory',
            index=models.Index(fields=['report', '-created_at'], name='idx_rrh_report_ts'),
        ),
    ]
