input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["your-topic"]
    group_id => "logstash-group"
    auto_offset_reset => "latest"
  }
}

filter {
  grok {
    match => {
      "message" => '%{IP:ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{URIPATHPARAM:path} HTTP/%{NUMBER:http_version}" %{NUMBER:status} %{NUMBER:bytes} "%{DATA:referrer}" "%{DATA:user_agent}"'
    }
  }

  date {
  match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
  target => "@timestamp"
  }

  mutate {
  convert => {
    "status" => "integer"
    "bytes" => "integer"
  }
}

}



output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-log"
  }
  stdout { codec => rubydebug }
}