input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["${KAFKA_TOPIC_RAW:log.raw}"]
    group_id => "logstash-group"
    auto_offset_reset => "latest"
    codec => "plain"
  }
}


filter {

  uuid {
    target => "event_id"
  }


  grok {
    match => {
      "message" => '%{IP:ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{DATA:path} HTTP/%{NUMBER:http_version}" %{NUMBER:status} %{NUMBER:bytes} "%{DATA:referrer}" "%{DATA:user_agent}"'
    }
  }


  if "_grokparsefailure" in [tags] {

    mutate {
      add_field => {
        "failure_reason" => "grok_parse_failed"
        "failed_stage" => "logstash_parser"
        "source_topic" => "${KAFKA_TOPIC_RAW:log.raw}"
      }
    }

  } else {


    date {
      match => [
        "timestamp",
        "dd/MMM/yyyy:HH:mm:ss Z"
      ]
      target => "@timestamp"
    }


    mutate {

      convert => {
        "status" => "integer"
        "bytes" => "integer"
      }


      add_field => {
        "log_source" => "nginx"
        "audit_user" => "%{ip}"
        "audit_event" => "%{method} %{path}"
        "[pipeline][rule_matching][status]" => "pending"
      }


      remove_field => [
        "message",
        "timestamp",
        "log"
      ]
    }
  }
}


output {


  if "_grokparsefailure" in [tags] {


    kafka {
      bootstrap_servers => "kafka:9092"
      topic_id => "${KAFKA_TOPIC_DLQ:log.dlq}"
      codec => json
    }


  } else {


    kafka {
      bootstrap_servers => "kafka:9092"
      topic_id => "${KAFKA_TOPIC_STRUCTURED:log.structured}"
      codec => json
    }

  }


  stdout {
    codec => rubydebug
  }
}