input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["log.raw"]
    group_id => "logstash-group"
    auto_offset_reset => "latest"
    codec => "plain"
  }
}

filter {

  uuid {
    target => "event_id"
  }

  grok {
    match => {
      "message" => '%{IP:ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{DATA:path} HTTP/%{NUMBER:http_version}" %{NUMBER:status} %{NUMBER:bytes} "%{DATA:referrer}" "%{DATA:user_agent}"'
    }
  }

  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
  }

  mutate {

    convert => {
      "status" => "integer"
      "bytes" => "integer"
    }

    add_field => {
      "log_source" => "nginx"
      "audit_user" => "%{ip}"
      "audit_event" => "%{method} %{path}"
      "[pipeline][rule_matching][status]" => "pending"
    }

    remove_field => ["message", "timestamp", "log"]
  }
}

output {

  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "log.audit"
    codec => json
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    document_id => "%{event_id}"
    index => "nginx-log-raw"
  }

  stdout {
    codec => rubydebug
  }
}